version: "3"
services:
  frontend:
    image: piotr04j/nest-angular
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/:/share/src/app/frontend
    working_dir: /share/src/app/frontend
    command: npm start -- --host 0.0.0.0
  backend:
    image: piotr04j/nest-angular
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/share/src/app/backend
    working_dir: /share/src/app/backend
    command: npm run start
