version: "3"
services:
  frontend:
    image: piotr04j/nest-angular:1.0.1
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/:/share/src/app/frontend
    command: sh -c "./start_frontend.sh"
  backend:
    image: piotr04j/nest-angular:1.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/share/src/app/backend
    command:  sh -c "./start_backend.sh"
    depends_on:
      - db
    links:
      - "db:db"
  db:
    image: postgres:9.6.22
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
