version: "3"
services:
  frontend:
    image: piotr04j/nest-angular:1.0.1
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/:/share/src/app/frontend
    command: sh -c "./start_frontend.sh"
  backend:
    image: piotr04j/nest-angular:1.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/share/src/app/backend
    command:  sh -c "./start_backend.sh"
