name: Node.js CI
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [ closed ]

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - run: npm --prefix ./backend ci
      - run: npm run --prefix ./backend build
      - run: npm --prefix ./backend test
  frontend-build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm --prefix ./frontend ci
      - run: npm run --prefix ./frontend build
      - run: npm --prefix ./frontend test
